### ISSUE TITLE
Missing volume mount

### ISSUE THREAD

**Issue by lanmarti** [containous/traefik-helm-chart#102]
I defined a volume in values.yaml, expecting it to be automatically mounted, however only the volume is defined in the final deployment.
values.yaml
```yaml
volumes:
- name: traefik-configuration
  mountPath: "/config"
  type: configMap
```
traefik deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  [...]
spec:
  [...]
  template:
    [...]
    spec:
      containers:
      - image: traefik:2.1.3
        name: traefik
        [...]
        volumeMounts:
        - mountPath: /data
          name: data
      [...]
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          defaultMode: 420
          name: traefik-configuration
        name: traefik-configuration
```
Is this a bug or are you supposed to define volume mounts separately in values.yaml (if so, what is the 'mountPath' field of `volumes` for)?
