### ISSUE TITLE
Entry point redirection and default routers configuration

### ISSUE THREAD

**Issue by gaui** [containous/traefik-helm-chart#109]
With the wonderful change in https://github.com/containous/traefik/pull/6417 it's now possible to configure automatic HTTP->HTTPS redirection for entrypoints. This issue proposes those changes to be configurable in the Helm chart as well.

Currently this could be done in `values.yml` like so:

```yaml
additionalArguments:
  - --entrypoints.web.address=:80
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.web.http.redirections.entryPoint.scheme=https
  - --entrypoints.websecure.address=:443
```

Maybe something like it's configured in the [YAML configuration](https://github.com/ldez/traefik/commit/ab87eb6ebf8a35707889a6035d6b11d39c4332c1#diff-3b2083d8cf4cbae556bcb9b51b234998R556):

```yaml
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          https: true
```
