### ISSUE TITLE
index.yaml missing

### ISSUE THREAD

**Issue by mash-graz** [containous/traefik-helm-chart#121]
when i try to install traefik2 without user intervention by putting this file in the `manifests` directory of k3s:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  repo: https://github.com/containous/traefik-helm-chart
  set:
    image.tag: "2.2"
    rbac.enabled: "true"
    ssl.enabled: "true"
```

i find this error in the log files:

```
+ helm_v3 repo add traefik https://github.com/containous/traefik-helm-chart
Error: looks like "https://github.com/containous/traefik-helm-chart" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/containous/traefik-helm-chart/index.yaml : 404 Not Found
```

**Comment by mmatur** [comment]
The URL of the helm chart is https://containous.github.io/traefik-helm-chart/index.yaml

The following yaml should work:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik/traefik
  repo: https://containous.github.io/traefik-helm-chart
  set:
    image.tag: "2.2"
```
