### ISSUE TITLE
Failing to setup traefik on AKS

### ISSUE THREAD

**Issue by Johnz86** [containous/traefik-helm-chart#124]
Hello Today I tried to setup Traefik on AKS based on this chart.

helm version: ```v3.1.0```
kubernetes: Client: v1.15.5, Server: v1.14.8

I did follow the steps on https://docs.traefik.io/providers/kubernetes-crd/ guide:

First I did apply the [definitions and RBAC](https://docs.traefik.io/reference/dynamic-configuration/kubernetes-crd/#definitions) with ```kubectl apply -f <traefik-definitions.yml>```

I created ingress resource:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traefik
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: eps-backend
          servicePort: 80
        path: /api(/|$)(.*)
      - backend:
          serviceName: eps-frontend
          servicePort: 80
        path: /(.*)
```
I installed the helm chart with:
``` 
helm repo add traefik https://containous.github.io/traefik-helm-chart
helm repo update
helm install traefik traefik/traefik
```
Then created the [resources](https://docs.traefik.io/reference/dynamic-configuration/kubernetes-crd/#resources):
```
k apply -f resources.yaml
traefikservice.traefik.containo.us/wrr2 created
traefikservice.traefik.containo.us/wrr1 created
traefikservice.traefik.containo.us/mirror1 created
traefikservice.traefik.containo.us/mirror2 created
ingressroute.traefik.containo.us/ingressroute created
ingressroutetcp.traefik.containo.us/ingressroutetcp.crd created
```
Now I see:
```
kubectl get svc
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                 AGE
eps-backend    ClusterIP      10.0.130.159   <none>          8008/TCP                                                6d
eps-frontend   ClusterIP      10.0.132.30    <none>          8000/TCP                                                6d
traefik        LoadBalancer   10.0.48.58     51.136.73.219   80:30263/TCP,443:30651/TCP                              13m

kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
eps-backend-d8469f576-cxd89     1/1     Running   0          25h
eps-frontend-6b4c5b7c58-9v5vd   1/1     Running   0          25h
traefik-7bbdfbf9d7-x6sch        1/1     Running   0          15m
 
kubectl describe ing traefik
Name:             traefik
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *
        /api(/|$)(.*)   eps-backend:80 ()
        /(.*)           eps-frontend:80 ()
Annotations:
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"networking.k8s.io/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"traefik","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"eps-backend","servicePort":80},"path":"/api(/|$)(.*)"},{"backend":{"serviceName":"eps-frontend","servicePort":80},"path":"/(.*)"}]}}]}}

Events:  <none>
```
When I head to my IP http://51.136.73.219/traefik it displays ```404 page not found```

When I look Into ```kubectl logs traefik-7bbdfbf9d7-x6sch```
```
time="2020-03-24T16:22:33Z" level=error msg="<nil>" namespace=default providerName=kubernetescrd ingress=ingressroute
time="2020-03-24T16:22:33Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." providerName=kubernetescrd ingress=ingressroute namespace=default
time="2020-03-24T16:22:33Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." namespace=default providerName=kubernetescrd ingress=ingressroute
time="2020-03-24T16:22:33Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." namespace=default providerName=kubernetescrd ingress=ingressroute
time="2020-03-24T16:22:33Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." ingress=ingressroute namespace=default providerName=kubernetescrd
time="2020-03-24T16:22:33Z" level=error msg="Error configuring TLS: secret default/foosecret does not exist" namespace=default providerName=kubernetescrd ingress=ingressroutetcp.crd
time="2020-03-24T16:22:33Z" level=error msg="Cannot create service: service not found" serviceName=whoamitcp servicePort=8080 ingress=ingressroutetcp.crd namespace=default providerName=kubernetescrd
time="2020-03-24T16:22:33Z" level=error msg="Error while building TraefikService: kubernetes service not found: default/s1" serviceName=wrr2 providerName=kubernetescrd
time="2020-03-24T16:22:33Z" level=error msg="Error while building TraefikService: kubernetes service not found: default/s3" providerName=kubernetescrd serviceName=wrr1
time="2020-03-24T16:22:33Z" level=error msg="Error while building TraefikService: kubernetes service not found: default/s1" providerName=kubernetescrd serviceName=mirror1
time="2020-03-24T16:22:33Z" level=error msg="Error while building TraefikService: kubernetes service not found: default/s2" providerName=kubernetescrd serviceName=mirror2
```
What steps did I do wrong? Why is the dashboard not accessible on  http://51.138.48.137/traefik ?
What rules can be given in ingress resource?

**Comment by mmatur** [comment]
Hi @Johnz86,

The only thing you have to do to install traefik on your AKS cluster is

```
helm repo add traefik https://containous.github.io/traefik-helm-chart
helm repo update
helm install traefik traefik/traefik
```

If you want to expose the dashboard you have to apply this `IngressRoute`:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```
Warning it will expose you dashboard publicly on the internet.  You can add authentication on it like it is describe [here](https://docs.traefik.io/operations/dashboard/#secure-mode)

I think your question is answered. I will close this issue.

If you have more question please ask on the [community forum](https://community.containo.us)
