### ISSUE TITLE
Traefik does not process correct Ingress objects

### ISSUE THREAD

**Issue by bronhy** [containous/traefik-helm-chart#1258]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

"27.0.2"

### What version of Traefik are you using?

v2.11.2

### What did you do?

Installed two instances of treafik. 
- namespace: ingress
- name: treafik

- namespace: ingress-internal
- name: treafik-internal

Add ingress route:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  rules:
  - host: api.development.fondsfinanz.systems
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /get
        pathType: Prefix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/mccutchen/go-httpbin:v2.15.0
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8080
```

This definition is read by both ingress instances. A route is produced in both instances.

```
Host(`api.development.fondsfinanz.systems`) && PathPrefix(`/get`)
websecure
websecure-default-httpbin-api-development-fondsfinanz-systems-get@kubernetes
default-httpbin-80
```
	
Using the following ingress definition results in no route by both instances

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  ingressClassName: treafik # notice ingress class name was added
  rules:
  - host: api.development.fondsfinanz.systems
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /get
        pathType: Prefix
```
Using the following ingress definition results in no route by both instances
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    kubernetes.io/ingress.class: traefik # notice ingress class name and annotation was added
spec:
  ingressClassName: treafik
  rules:
  - host: api.development.fondsfinanz.systems
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /get
        pathType: Prefix
```

Using the following ingress definition results in a route by both instances

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    kubernetes.io/ingress.class: traefik. # notice the annotation but no ingressClassName
spec:
  rules:
  - host: api.development.fondsfinanz.systems
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /get
        pathType: Prefix
```
Setup only works if I
**First option:** do not to use any additional keys
**Second option:** use **only** annotation

In both cases both of the instances will have the route but I only want one

### What did you see instead?

I have no solution yet for kind ingress. Kind ingressroute works correct

### What is your environment & configuration?

public args
```
  containers:
  - args:
    - --global.checknewversion
    - --global.sendanonymoususage
    - --entrypoints.metrics.address=:9100/tcp
    - --entrypoints.traefik.address=:9000/tcp
    - --entrypoints.web.address=:8000/tcp
    - --entrypoints.websecure.address=:8443/tcp
    - --api.dashboard=true
    - --ping=true
    - --metrics.prometheus=true
    - --metrics.prometheus.entrypoint=metrics
    - --providers.kubernetescrd
    - --providers.kubernetescrd.allowExternalNameServices=true
    - --providers.kubernetescrd.allowEmptyServices=true
    - --providers.kubernetesingress
    - --providers.kubernetesingress.allowExternalNameServices=true
    - --providers.kubernetesingress.allowEmptyServices=true
    - --entrypoints.web.http.redirections.entryPoint.to=:443
    - --entrypoints.web.http.redirections.entryPoint.scheme=https
    - --entrypoints.websecure.http.tls=true
    - --accesslog=true
    - --accesslog.format=json
    - --accesslog.fields.defaultmode=drop
    - --accesslog.fields.names.StartUTC=keep
    - --accesslog.fields.names.ClientHost=keep
    - --accesslog.fields.names.DownstreamContentSize=keep
    - --accesslog.fields.names.DownstreamStatus=keep
    - --accesslog.fields.names.Duration=keep
    - --accesslog.fields.names.OriginStatus=keep
    - --accesslog.fields.names.RequestAddr=keep
    - --accesslog.fields.names.RequestMethod=keep
    - --accesslog.fields.names.RequestPath=keep
    - --accesslog.fields.names.RequestProtocol=keep
    - --accesslog.fields.names.RequestScheme=keep
    - --accesslog.fields.names.RouterName=keep
    - --accesslog.fields.names.ServiceName=keep
    - --accesslog.fields.names.TLSVersion=keep
    - --accesslog.fields.names.level=keep
    - --accesslog.fields.names.time=keep
    - --providers.kubernetesCRD.ingressclass=traefik
```

private args

```
  containers:
  - args:
    - --global.checknewversion
    - --global.sendanonymoususage
    - --entrypoints.metrics.address=:9100/tcp
    - --entrypoints.traefik.address=:9000/tcp
    - --entrypoints.web.address=:8000/tcp
    - --entrypoints.websecure.address=:8443/tcp
    - --api.dashboard=true
    - --ping=true
    - --metrics.prometheus=true
    - --metrics.prometheus.entrypoint=metrics
    - --providers.kubernetescrd
    - --providers.kubernetescrd.allowExternalNameServices=true
    - --providers.kubernetescrd.allowEmptyServices=true
    - --providers.kubernetesingress
    - --providers.kubernetesingress.allowExternalNameServices=true
    - --providers.kubernetesingress.allowEmptyServices=true
    - --entrypoints.web.http.redirections.entryPoint.to=:443
    - --entrypoints.web.http.redirections.entryPoint.scheme=https
    - --entrypoints.websecure.http.tls=true
    - --accesslog=true
    - --accesslog.format=json
    - --accesslog.fields.defaultmode=drop
    - --accesslog.fields.names.StartUTC=keep
    - --accesslog.fields.names.ClientHost=keep
    - --accesslog.fields.names.DownstreamContentSize=keep
    - --accesslog.fields.names.DownstreamStatus=keep
    - --accesslog.fields.names.Duration=keep
    - --accesslog.fields.names.OriginStatus=keep
    - --accesslog.fields.names.RequestAddr=keep
    - --accesslog.fields.names.RequestMethod=keep
    - --accesslog.fields.names.RequestPath=keep
    - --accesslog.fields.names.RequestProtocol=keep
    - --accesslog.fields.names.RequestScheme=keep
    - --accesslog.fields.names.RouterName=keep
    - --accesslog.fields.names.ServiceName=keep
    - --accesslog.fields.names.TLSVersion=keep
    - --accesslog.fields.names.level=keep
    - --accesslog.fields.names.time=keep
    - --providers.kubernetesCRD.ingressclass=traefik-internal
```

### Additional Information

```shell

```

**Comment by bronhy** [comment]
Additional information: 
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    annotations:
      ingressclass.kubernetes.io/is-default-class: "false"  # notice the class is set to false 
      meta.helm.sh/release-name: traefik
      meta.helm.sh/release-namespace: ingress
    creationTimestamp: "2024-11-15T12:11:26Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: traefik-ingress
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: traefik
      helm.sh/chart: traefik-27.0.2
    name: traefik
    resourceVersion: "2087047"
    uid: 41c3c0bd-542b-4cc8-9214-4dc9b36924c7
  spec:
    controller: traefik.io/ingress-controller
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    annotations:
      ingressclass.kubernetes.io/is-default-class: "false"  # notice the class is set to false 
      meta.helm.sh/release-name: traefik-internal
      meta.helm.sh/release-namespace: ingress-internal
    creationTimestamp: "2024-11-19T13:20:13Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: traefik-internal-ingress-internal
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: traefik
      helm.sh/chart: traefik-27.0.2
    name: traefik-internal
    resourceVersion: "2169766"
    uid: daa6ed31-928a-40a6-a27f-ed9657c61324
  spec:
    controller: traefik.io/ingress-controller
kind: List
metadata:
  resourceVersion: ""

**Comment by vidarno** [comment]
Hi,

I think you want to set
    - --providers.kubernetesingress.ingressClass=traefik-internal
 and
    - --providers.kubernetesingress.ingressClass=traefik
in your respective traefik-instances to make sure they listen only to "their" ingressClass.
Please also note that in two of your examples you have a typo, using "treafik" (instead of traefik) as the ingressClassName, which doesn't help :)

**Comment by mloiseleur** [comment]
@bronhy Does that answer your question ?

**Comment by bronhy** [comment]
Let me try this and I will report back.

**Comment by bronhy** [comment]
```
 --providers.kubernetesingress.ingressClass=traefik-internal
```
Added to traefik internal

```
 --providers.kubernetesingress.ingressClass=traefik
```
Added to treafik

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  rules:
  - host: api.development.internal.fondsfinanz.systems
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /get
        pathType: Prefix
```

The above config will create the routes in correct treafik


```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  ingressClassName: treafik-internal
  rules:
  - host: api.development.internal.fondsfinanz.systems
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /get
        pathType: Prefix
```
The above config creates no route

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  ingressClassName: treafik-internal
  rules:
  - host: api.development.internal.fondsfinanz.systems
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /get
        pathType: Prefix
```
The above config creates no routes

Looks like I just didn't know how to configure it properly. Thank you @vidarno 

This issue can be closed.
