### ISSUE TITLE
Exposing metrics port

### ISSUE THREAD

**Issue by cunhazord** [containous/traefik-helm-chart#134]
If someone wants to consume the metrics from traefik, shouldn't the values.yaml have like:
```
  metrics:
    port: 8082
    expose: true
    exposedPort: 8080
```

on ports?
If not, i cant access the metrics on prometheus

**Comment by mmatur** [comment]
If you want to expose your metrics this is something you can do by adding the following yaml in you `values.yaml` file.

```yaml
  metrics:
    port: 8082
    expose: true
    exposedPort: 8080
```


But we don't want to add it by default for security reason.

The question is answered so I am closing this issue

**Comment by holmesb** [comment]
For anyone else trying to setup Prometheus monitoring, the full path is:
```
ports:
  metrics:
    port: 8082
    expose: true
    exposedPort: 8080
```
