### ISSUE TITLE
serversTransport.insecureSkipVerify & Chart v36.0.0

### ISSUE THREAD

**Issue by vember31** [containous/traefik-helm-chart#1440]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

36.0.0

### What version of Traefik are you using?

3.4.1

### What did you expect to happen ?

Sites behind Traefik proxy that utilize https shouldn't need to have their certs verified when the below is defined in the helm values. Those sites should work & Traefik shouldn't throw a 500.

```
    globalArguments:
    - "--serversTransport.insecureSkipVerify=true"
 ```
I didn't think this argument specifically was impacted by the move to 36.0.0, but maybe it is / was.

### What did you notice instead ?

Upon upgrading from chart v35.4.0 to v36.0.0, I'm seeing the following in Traefik logs, and the site is not accessible & Traefik throws a 500. It's almost like chart v36.0.0 is not recognizing the above argument anymore or something changed that I need to update in my config that I wasn't aware of / couldn't find details on :)

`tls: failed to verify certificate: x509: cannot validate certificate for [insert random k8s service IP] because it doesn't contain any IP SANs`

If I roll back to chart v35.4.0, with no changes to my helm values or anything else, the issue is resolved. 

Also please feel free to update the title if this issue can be better defined/described. Thank you!!

### What are your values ?

```
   ingressRoute:
      dashboard:
        enabled: false

    globalArguments:
    - "--api.insecure=true"
    - "--serversTransport.insecureSkipVerify=true"

    additionalArguments: 
       - "--log.level=DEBUG"

    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 9100
        expose: 
          default: true
          internal: false
        protocol: TCP

    service:
      enabled: true
      single: true
      type: LoadBalancer
      spec: 
        loadBalancerIP: "${TRAEFIK_IP}"
        externalTrafficPolicy: Local #for ipallowlisting detection. 

    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true

    rbac:
      enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true

    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true

      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
        ingressClass: traefik
        ingressEndpoint:
          ip: "${TRAEFIK_IP}"
```

### Additional Information

```shell

```
