### ISSUE TITLE
Getting CrashLoopBackOff for Traefik pod with 'field not found, node: tls' error when specifying TLS additional arguments

### ISSUE THREAD

**Issue by atoy3731** [containous/traefik-helm-chart#146]
I'm trying to transition from the Kubernetes ingress provider to CRD via Helm, but my Traefik pod won't start due to the following error:
```
2020/04/07 18:26:45 command traefik error: failed to decode configuration from flags: field not found, node: tls
```

I deployed via Helm using the following command:
```
helm upgrade --install -n traefik traefik traefik/traefik -f values.yaml
```

and the following `values.yaml` pulled from this repo and modified:
```
image:
  name: traefik
  tag: 2.2.0

deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}

ingressRoute:
  dashboard:
    enabled: true
    annotations: {}

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

additionalArguments:
- "--tls.certificates.certFile=/certs/tls.crt"
- "--tls.certificates.keyFile=/certs/tls.key"

volumes:
- name: certs
  mountPath: "/certs"
  type: secret

globalArguments:
  - "--global.checknewversion"

env: []

ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
  web:
    port: 8000
    expose: true
    exposedPort: 80
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    
service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  spec: {}
  loadBalancerSourceRanges: []
  externalIPs: []
    
autoscaling:
  enabled: false

hostNetwork: false
serviceAccountAnnotations: {}
resources: {}
affinity: {}
nodeSelector: {}
tolerations: []
```

I've confirmed that my `certs` secret exists in the namespace and is valid (if it wasn't, the pod wouldn't even start).
