### ISSUE TITLE
Traefik Dashboard on Rancher UI

### ISSUE THREAD

**Issue by AndreasBBS** [containous/traefik-helm-chart#1528]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'd like for the link `https://rancher.my.instance/api/v1/namespaces/kube-system/services/http:traefik-dashboard:80/proxy/dashboard/#/` to display the dashboard correctly.

I created a service for the dashboard as follows
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: traefik
  selector:
    app.kubernetes.io/name: traefik
  type: ClusterIP
```

When I access with `kubectl port-forward service/traefik-dashboard 9000:80 -n kube-system` it works flawlessly.

When I access with through Rancher at `https://rancher.my.instance/api/v1/namespaces/kube-system/services/http:traefik-dashboard:80/proxy/dashboard/#/`
It fails because it's trying to communicate with the api at `https://rancher.my.instance/api/overview` instead of using the correct link that would be `https://rancher.my.instance/api/v1/namespaces/kube-system/services/http:traefik-dashboard:80/proxy/api/overview`
This is probably something simple to fix in the UI code. If anyone wants to point me in the right direction I can try and make a pull request. Longhorn's frontend does this well where I can access both through `kubectl port-forward` as well as the Rancher link so I know it's possible.

Thanks for the attention and looking forward to be able to make this a reality. Maybe with this fixed we can get Traefik to show up in Rancher's app bar like longhorn does.
![Screenshot from 2023-10-31 17-03-19](https://github.com/traefik/traefik-helm-chart/assets/12399440/6bd21c06-abb6-4b7f-be78-f2ef1b476df7)
