### ISSUE TITLE
Mount TLS certs via cli not working

### ISSUE THREAD

**Issue by r3kzi** [containous/traefik-helm-chart#160]
Hi,

i was trying to mount  a cert pair via Kubernetes secrets.

I was following https://github.com/containous/traefik-helm-chart/blob/master/traefik/values.yaml#L32-L45

My configuration is:
```
additionalArguments:
  - "--providers.kubernetesIngress=true"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.entryPoint=metrics"
  - "--tls.certificates.certFile=/certs/tls.crt"
  - "--tls.certificates.keyFile=/certs/tls.key"

volumes:
  - name: public-cert
    mountPath: "/certs"
    type: secret
```

Yet it gives me following error:
``` 
$ k logs -n kube-system traefik-78545999d5-rrlf5
2020/04/23 09:48:14 command traefik error: failed to decode configuration from flags: field not found, node: tls
```
