### ISSUE TITLE
Default values on `securityContext` will render the container useless

### ISSUE THREAD

**Issue by zzvara** [containous/traefik-helm-chart#163]
With the current default values related to `securityContext`, the container would not start. As using `HelmReleases`, a rolling upgrade could break Traefik.

When starting a container with default values, the container:
- may not use the `acme` settings from volume, since it is "too open",
- moreover, binding to port 80 will fail with "permission denied".

As a quick fix, we are using these settings:
```
securityContext:
      capabilities:
        drop: []
        add:
          - ALL
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    podSecurityContext:
      fsGroup: 0
```

Although there might be security issues related to the above setting, we are going to look into `securityContext`, since we have never used it.

Moreover, problems like "too open" in regard to `acme` configuration should be documented in the light of `securityContext` feature of this Helm chart.
