### ISSUE TITLE
Traefik can't create acme.json (read-only filesystem, permission denied)

### ISSUE THREAD

**Issue by Jawastew** [containous/traefik-helm-chart#165]
With the new securityContext from #155 I can no longer mount a pv with the default settings.
```
kubectl logs -n kube-system service/traefik
...
time="2020-04-27T18:43:23Z" level=error msg="The ACME resolver \"letsencrypt-test\" is skipped from the resolvers list because: unable to get ACME account: open acme.json: read-only file system"
time="2020-04-27T18:43:23Z" level=error msg="The ACME resolver \"le\" is skipped from the resolvers list because: unable to get ACME account: open /data/acme.json: permission denied"
```

When I try to access my mounted /data volume, it is owned by root by default and I can't read or create files. Even after I chown the directory on the host machine where the volume is mounted I still can't write to the directory because of the ```securityContext.readOnlyRootFilesystem = true``` default.

my helm values:
```
...
persistence:
  enabled: true
  storageClass: export-nfs
  accessMode: ReadWriteMany
  subPath: "traefik"
  size: 1Gi
...
```

When I add:
```
securityContext:
  readOnlyRootFilesystem: False
```
I am able to get rid of the read-only filesystem warning, but I am still getting 'permission denied'.

To get everything running again under the default root user you need the following chart values:
```
securityContext:
  readOnlyRootFilesystem: False
  runAsGroup: 0
  runAsUser: 0
  runAsNonRoot: false
```

I would propose to change the security context back to a root user as default, since this will not introduce any breaking changes when updating from an earlier version of the helmchart where the acme.json would be owned by root by default.

**Comment by SimonTheLeg** [comment]
Can you share your whole values.yml?

With these settings I am still stuck one step earlier (same as #164) at:

```
time="2020-04-29T09:56:43Z" level=error msg="The ACME resolver \"le\" is skipped from the resolvers list because: unable to get ACME account: permissions 660 for /data/acme.json are too open, please use 600"
```

**Comment by Jawastew** [comment]
values.yaml
```yaml
image.tag: "2.2.0"
service:
persistence:
  enabled: true
  storageClass: export-nfs
  accessMode: ReadWriteMany
  subPath: "traefik"
  size: 1Gi
securityContext:
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsUser: 0
  runAsNonRoot: false
additionalArguments:
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--certificatesResolvers.letsencrypt-test.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesResolvers.letsencrypt-test.acme.dnsChallenge=true"
  - "--certificatesResolvers.letsencrypt-test.acme.dnsChallenge.provider=cloudflare"
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log.level=DEBUG"
env:
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: cf-api-key
        key: key
  - name: CF_API_EMAIL
    value: "xxxx"
```

I saw your comment on #164 it looks like this might be an issue with the way your storage backend works?

When I delete my pod the acme.json retains its permissions. I'm using rook nfs as a backend.
```
$ kubectl delete -n kube-system pod traefik-5676f9cfcd-hc46h
pod "traefik-5676f9cfcd-hc46h" deleted
$ kubectl exec -n kube-system -it Service/traefik -- sh
/ # cd /data
/data # ls -la
total 8
drwx--x--x    2 nobody   42949672      4096 Apr 27 18:55 .
drwxr-xr-x    1 root     root          4096 Apr 29 13:06 ..
-rw-------    1 nobody   42949672         0 Apr 27 18:55 acme.json
-rw-r--r--    1 nobody   42949672         0 Apr 27 18:54 test
/data # 
```
Not sure about the ownership of my files there, but I'm not getting any errors as far as I can tell.
