### ISSUE TITLE
Traefik behaves as if using port 8443 externally (instead of 443)

### ISSUE THREAD

**Issue by sdenel** [containous/traefik-helm-chart#173]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

* I followed official documentation to install Traefik using Helm 3: https://docs.traefik.io/getting-started/install-traefik/#use-the-helm-chart
* I added a custom value to get HTTP to https redirection:
`additionalArguments:
    - --entrypoints.web.http.redirections.entrypoint.to=websecure`

### What did you expect to see?

I expected http://toto.com to redirect requests to https://toto.com

### What did you see instead?
* http://toto.com redirects to https://toto.com:8443
* Can be explained by the fact that traefik in launched with --entryPoints.websecure.address=:8443 by the Helm template to avoid root privileges (perfectly understandable from a security point of view, **if** it was working...)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:2.2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Standard, bare-metal Kubernetes

**Comment by sdenel** [comment]
This is the values I had to customize to go forward (sadly running the container as root, yet with limited capabilities):
`ports:
  web:
    port: 80
  websecure:
    port: 443
securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
  runAsNonRoot: false
  runAsUser: 0`

**Comment by ldez** [comment]
Hello,

The redirection can be defined like that:

```
additionalArguments: 
- --entrypoints.web.http.redirections.entrypoint.to=433
- --entrypoints.web.http.redirections.entrypoint.scheme=https
```

**Comment by sdenel** [comment]
Hi @ldez ,
thanks for your suggestion. Yet, it gives me this error:
`time="2020-05-02T18:11:56Z" level=error msg="'to' entry point field references a non-existing entry point: 433" providerName=internal entryPointName=web`

**Comment by ldez** [comment]
Check your Traefik version, it must be 2.2.1

**Comment by sdenel** [comment]
Yes, it is:
```bash
$ k -n traefik-v2 get deployments.apps traefik -o json | jq -r '.spec.template.spec.containers[0].image'
traefik:2.2.1
```

**Comment by ldez** [comment]
Sorry mistake in my example:

```yml
additionalArguments: 
- --entrypoints.web.http.redirections.entrypoint.to=:433
- --entrypoints.web.http.redirections.entrypoint.scheme=https
```

**Comment by sdenel** [comment]
Thanks @ldez, not that intuitive, but your solution works!

**Comment by myco** [comment]
I have same issue after upgrading to 2.2.1 , chart 8.1.4

we need to change
--entrypoints.web.http.redirections.entryPoint.to=**websecure**
to
when I have --entrypoints.web.http.redirections.entryPoint.to=**:443**

**Comment by productfrontenddeveloper** [comment]
I also have the same problem, it was not solved. Can you help me ? 

```
        - --entryPoints.web.address=:8000
        - --entryPoints.websecure.address=:8443
        - --entrypoints.web.http.redirections.entrypoint.to=:8443
        - --entrypoints.web.http.redirections.entrypoint.scheme=https
 ```
 
 ```
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aa
  template:
    metadata:
      labels:
        app: aa
    spec:
      containers:
      - name: aa
        image: aa/aa
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: a
---
apiVersion: v1
kind: Service
metadata:
  name: aa-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    app: aa
---
```


```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aa-ingress
spec:
  rules:
    - host: aa.test.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aa-svc
                port:
                  number: 80
```

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: aatest
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`aa.test.com`)
      kind: Rule
      services:
        - name: aa-svc
          port: 80
  tls:
    secretName: aa-cert
 ```

**Comment by tingwei628** [comment]
I used myvalues.yaml and it worked.
It didn't need `securityContext: add: [NET_BIND_SERVICE]`

>chart version: 33.0.0
app version: v3.2.0

```yaml
# myvalues.yaml
ports:
  web:
    redirectTo:
      port: websecure

#### skip it
#securityContext:
#  capabilities:
#    drop: [ALL]
#    add: [NET_BIND_SERVICE]
#  readOnlyRootFilesystem: true
#  runAsGroup: 0
#  runAsNonRoot: false
#  runAsUser: 0

```
