### ISSUE TITLE
Cannot gather all metrics when replicas > 1

### ISSUE THREAD

**Issue by blueabysm** [containous/traefik-helm-chart#176]
I install traefik v2 via helm along with the following `values.yaml` and get metrics in prometheus through this URL:
```
http://traefik.<namespae>.svc.cluster.local:8082/metrics
```
At the beginning, the `replicas` field is default to `1`.
After I modify it to `2`, `traefik_service_requests_total` drops down to half of it was.
And then I change it to `4`, `traefik_service_requests_total` drops down to 1/4.
Seems that every time I send a request to `/metrics`, it goes to only one pod behind the traefik service, and the pod only knows metrics about itself.

How do you guys get the total request count? 
Any help would be appreciated.

````yaml
additionalArguments:
  - "--accesslog=true"
  - "--accesslog.format=json"
  - "--accesslog.fields.defaultmode=keep"
  - "--accesslog.fields.headers.defaultmode=keep"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.entryPoint=metrics"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--entryPoints.metrics.address=:8082"
  - "--metrics.prometheus.entryPoint=metrics"

rbac:
  enabled: true

deployment:
  enabled: true

nodeSelector:
  node-role.kubernetes.io/webserver: "true"

ports:
  web:
    nodePort: 30080
    exposedPort: 80
    expose: true
  websecure:
    nodePort: 30443
    exposedPort: 443
    expose: true
  metrics:
    port: 8082
    exposedPort: 8082
    expose: true

service:
  enabled: true
  type: LoadBalancer

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 16
````

**Comment by blueabysm** [comment]
Hi @SantoDE . I notice that this thread has been marked as `question` for days. What could I do to provide more details? I'm glad to :)
After googling these days, I found these two topics discussing similar:
https://github.com/containous/traefik/issues/2966
https://community.containo.us/t/how-to-aggregate-all-pods-prometheus-metrics/3971/2

**Comment by SantoDE** [comment]
Hey!

It was on my list for answer today, so nothing for you.

The "issue" you're facing is, that every traefik instance is on its own when replicated and thus, not all instances are aware of all metrics. Depending on which Traefik instance prometheus is scrapping that (based on the k8s service forwarding the request to ANY instance) you have different / not all metrics.

You could try to scrap from all pod's seperately and aggregate somehow, but it's sadly nothing Traefik could do for you automatically.

As this is a question (and hopefully answered), I'll close that issue now.

**Comment by blueabysm** [comment]
> Hey!
> 
> It was on my list for answer today, so nothing for you.
> 
> The "issue" you're facing is, that every traefik instance is on its own when replicated and thus, not all instances are aware of all metrics. Depending on which Traefik instance prometheus is scrapping that (based on the k8s service forwarding the request to ANY instance) you have different / not all metrics.
> 
> You could try to scrap from all pod's seperately and aggregate somehow, but it's sadly nothing Traefik could do for you automatically.
> 
> As this is a question (and hopefully answered), I'll close that issue now.

Glad to get your reply! Seems I'm on the right way to work it out currently 😄

**Comment by blueabysm** [comment]
### Solution for people who has the same problem:

Actually we need to config Prometheus but not Traefik.

Originally I used this following section in my `prometheus-server` configmap:
```yaml
scrape_configs:
- job_name: 'Traefik'
  metrics_path: /metrics
  params:
    module: [http_prometheus]
  static_configs:
  - targets: ['traefik.site.svc.cluster.local:8082']
```
What I missed is a `role` for the job like this.
```yaml
scrape_configs:
- job_name: 'Traefik'
  metrics_path: /metrics
  params:
    module: [http_prometheus]
  static_configs:
  - targets: ['localhost:8082']
  kubernetes_sd_configs:
  - role: endpoints
```

After that, the `instance` tag of metrics are filled with `<pod ip>:8082`. Then you can query the total requests like this in Grafana:
```
sum(rate(traefik_entrypoint_requests_total[2m])) by (instance)
```
