### ISSUE TITLE
RBAC only looks at `extensions/ingresses`

### ISSUE THREAD

**Issue by mjpitz** [containous/traefik-helm-chart#200]
This version of the traefik chart is not compatible with the latest definition of the `Ingress` resource.

Right now, permissions are only granted on `extensions/ingress`. For this to work with newer ingress definitions, we  need to update the the ingress operations in RBAC to support `networking.k8s.io/ingresses`.

**Comment by mjpitz** [comment]
There's probably a code-change associated with this too. Possibly a client version upgrade.

**Comment by SantoDE** [comment]
Hello @mjpitz,

thanks a lot for your interest.

I tried to reproduce your request, but I sadly can't. 

I tested with the helm chart and the following definitions

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-http
  labels:
    app: whoami-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-http
  template:
    metadata:
      labels:
        app: whoami-http
    spec:
      containers:
      - name: whoami
        image: containous/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-http
spec:
  selector:
    app: whoami-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami-http
spec:
  rules:
  - host: webapp.docker.localhost
    http:
      paths:
      - path:
        backend:
          serviceName: whoami-http
          servicePort: 80
```

and Traefik is perfectly fine with the Ingress through the `networking` API Group. Maybe there's some mapping inside k8s for that?

Please let me know if you have a configuration which errors out :-)
