### ISSUE TITLE
Error getting LE certs with ingressroute tls.domains.main and tls.domains.sans configured

### ISSUE THREAD

**Issue by mojochao** [containous/traefik-helm-chart#204]
I am trying to configure a Traefik (v2.2.1) IngressRoute CRD resource as follows with the incubating traefik 2 chart (v8.6.1) in github at https://github.com/containous/traefik-helm-chart/tree/master/traefik:

```
ingressroute:
    enabled: true
    tls:
        enabled: true
        certResolver: production
        domains:
            main: prod0.api.spadash.com
            sans:
            - prod.api.spadash.com
            - spadash.com
```
When I look at my traefik logs I see the following:

```
time="2020-06-21T02:16:35Z" level=info msg="Starting provider *acme.Provider {\"email\":\"vendor@spadash.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/data/acme.json\",\"keyType\":\"RSA4096\",\"dnsChallenge\":{\"provider\":\"route53\",\"delayBeforeCheck\":5000000000},\"ResolverName\":\"production\",\"store\":{},\"ChallengeStore\":{}}"
time="2020-06-21T02:16:35Z" level=info msg="Testing certificate renew..." providerName=production.acme
time="2020-06-21T02:16:37Z" level=error msg="Unable to obtain ACME certificate for domains \"prod0.api.spadash.com,prod.api.spadash.com spadash.com\" : unable to generate a certificate for the domains [prod0.api.spadash.com prod.api.spadash.com spadash.com]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"prod.api.spadash.com spadash.com\": Domain name contains an invalid character, url: " providerName=production.acme
```

Why is Traefik joining all domains.main and domains.sans hostnames with a space when requesting certs? Is this a bug in my chart configuration, in the helm chart, or in Traefik itself?

Many thanks in advance.

**Comment by SantoDE** [comment]
Hello @mojochao,

maybe its just because of monday morning, but where are you setting that configuration from above? I'd like to try and reproduce.

**Comment by VeryStrongFingers** [comment]
@SantoDE it looks like a subchart, which is overloading https://github.com/containous/traefik-helm-chart/blob/8a64eda117418f9e2775b11a29a720e00cf199f1/traefik/crds/ingressroute.yaml

I'm going to be trying this myself. Will let you know how it goes

**Comment by mojochao** [comment]
I'm setting it in my values file used when installing the chart.

**Comment by DirtyCajunRice** [comment]
Couple things here:
1. This is not a template of the traefik-helm-chart but of your own making, so im not sure that this repo is the right place for this support request
That said...
You did not render the sans as an actual list. You just pointed at it. a YAML structured lists are either in [block collection form](https://yaml.org/spec/1.2/spec.html#style/block/collection) or flattened into a comma delimited array via [flow styles](https://yaml.org/spec/1.2/spec.html#style/flow/)
Next time just format it like you got it and you will be safer.
```yaml
{{- if .Values.ingressroute.tls.enabled }}
  tls:
    certResolver: {{ .Values.ingressroute.tls.certResolver }}
    domains:
      - main: {{ .Values.ingressroute.tls.domains.main }}
        {{- with .Values.ingressroute.tls.domains.sans }}
        sans:
        {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
```
