### ISSUE TITLE
Add providers.kubernetesingress.ingressendpoint.publishedservice in template

### ISSUE THREAD

**Issue by Daverkex** [containous/traefik-helm-chart#207]
To integrate [External DNS](https://github.com/kubernetes-sigs/external-dns) with Traefik [is necessary to enable published service](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#alias).

This flag requires a namespace and service (usually the Traefik LoadBalancer service if it's the default ingress controller). For this reason is perfect to integrate in the Helm chart.

Proposal:
A new config extension:
```yaml
providers:
  kubernetesIngress:
    publishedService:
      enabled: false
      pathOverride: ""
```

If "pathOverride" is unset and "enabled" true use chart namespace and Traefik LoadBalancer service.

This proposal is based on [Nginx ingress controller Helm Chart](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L88)

Traefik documentation: https://docs.traefik.io/providers/kubernetes-ingress/#publishedservice
