### ISSUE TITLE
Not able to redirect from http to https 

### ISSUE THREAD

**Issue by zeroone-shreeram** [containous/traefik-helm-chart#208]
is there any trick i can do to make http to https redirect work?

added  --entrypoints.web.http.redirections.entryPoint.scheme=https in additionalArguments but it didn't work.

but when i add these two arguments while deployment from helm chart:
--entrypoints.web.http.redirections.entryPoint.to=websecure --entrypoints.websecure.http.tls.certResolver=default

but when i browsed the URL it redirected me to example.com:8443/tpc.

is this a bug in traefik ingress controller or am i m doing it wrong?

**Comment by SantoDE** [comment]
Can you post your whole configuration files please?

**Comment by akhfa** [comment]
Hi

> Can you post your whole configuration files please?

I think I can answer this question because I see same additional `/tcp` path when redirecting into https

I install traefik using helm, listen port 80 and 443. This is my helm values version 8.9.0
```yaml
additionalArguments:
  - "--providers.kubernetesingress.ingressclass=some-ingress-classname"
  - "--certificatesresolvers.letsprod.acme.tlschallenge=true"
  - "--certificatesresolvers.letsprod.acme.email=someemail@gmail.com"
  - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
ingressRoute:
  dashboard:
    enabled: false
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 0
hostNetwork: true
persistence:
  enabled: true
ports:
  web:
    port: 80
    hostPort: 80
  websecure:
    port: 443
    hostPort: 443
rbac:
  namespaced: true
securityContext: null
```

And then I deploy adminer by using helm chart https://cetic.github.io/helm-charts latest version, with this values
```yaml
service:
  type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: some-ingress-classname
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsprod
  hosts:
    - somedomain.com
resources:
  limits:
    cpu: 100m
    memory: 128Mi
```

After I hit the domain, this is the result
```
$ curl -I somedomain.com
HTTP/1.1 308 Permanent Redirect
Location: https://somedomain.com:443/tcp/
Date: Fri, 10 Jul 2020 12:54:19 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```
Please see the `Location` comes to wrong path `Location: https://somedomain.com:443/tcp/`

After somedays searching the root cause, finally I can narrow down the issue.
When I use helm chart to deploy traefik, the parameters will become like this
```
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:80/tcp
        - --entryPoints.websecure.address=:443/tcp
```
I tried to edit the traefik deployment file manually into this
```
        - --entryPoints.traefik.address=:9000
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443
```
And finally, the redirect issue will be fixed
```
$ curl -I somedomain.com
HTTP/1.1 308 Permanent Redirect
Location: https://somedomain.com/
Date: Fri, 10 Jul 2020 13:01:23 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

But in the first place, I'm not sure what the additional `/tcp` do in the `--entryPoints` parameter. Can we remove it as default?

If yes, I already create https://github.com/containous/traefik-helm-chart/pull/219

Thank you

**Comment by akhfa** [comment]
Hi @zeroone-shreeram 

For your `:8443` issue, can you try to add `--entrypoints.websecure.address=:443` ?
I don't have this issue yet, so I'm also not sure, but I think explicit websecure.address may solve this issue 🤔 

Sources:
https://docs.traefik.io/migration/v1-to-v2/#http-to-https-redirection-is-now-configured-on-routers

**Comment by SantoDE** [comment]
Hello @akhfa,

I was able to pin down the issue in Traefik itself. I've raised a PR on update to address that behavior. https://github.com/containous/traefik/pull/7047

**Comment by akhmadfld** [comment]
Hi @SantoDE,

Thanks a lot for your help. I will wait for the release 😁

**Comment by monotek** [comment]
Is this already implemented in the current image 2.2.8?
If so, whats the correct config to enbale https redirectt for all k8s ingresses?

**Comment by monotek** [comment]
Got it working now. This is the helm config which works for me:

```
    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"

    ports:
      websecure:
        port: 443

    securityContext: ""
```

**Comment by SantoDE** [comment]
Cool! I'll close that one then.

**Comment by monotek** [comment]
@SantoDE 
Is there any way to do this without the need to use port 443 and the root user?
I don't fully understand why an https redirect, which points to the fqdn, needs to be done internally with port 443?

**Comment by viceice** [comment]
this is not yet fixed, as the chart is using version 2.2.5 of traefik

https://github.com/containous/traefik-helm-chart/blob/8a64eda117418f9e2775b11a29a720e00cf199f1/traefik/values.yaml#L4

bugfix was release on [2.2.6](https://github.com/containous/traefik/releases/tag/v2.2.6)

ref #226

**Comment by monotek** [comment]
I've used image 2.3.0-rc3

**Comment by viceice** [comment]
@monotek sure, but the default image / chart isn't fixed, so one have to override the image tag.

**Comment by monotek** [comment]
Yes, i know. 
I just wanted to back you, that i've got it working with a newer version ;-)

**Comment by SantoDE** [comment]
There is now a new version of the helm chart, which includes Traefik 2.2.8. Feel free to give it a test ;)

**Comment by monotek** [comment]
Works with 2.2.8 too. Looking forward to see 2.3.0 final 😎

**Comment by lexfrei** [comment]
Is there any best practice for HTTP -> HTTPS redirection with this chart?
Looks like this is not enough to redirect to 443 port, but I can't figure out how to do the redirection.
```yaml
        ports:
          web:
            redirectTo: websecure
```

**Comment by monotek** [comment]
I've switched to contour as its not possible to get proper redirect with kubernetes default ingress.
If you do it as described above, you can't use CertManager HTTP challenge, because its redirected to HTTPS too.
I guess you have to use ingressroute crd to get it working but with this you'll loose support for other tools relyin on ingress, like external-dns.

**Comment by miend** [comment]
> I guess you have to use ingressroute crd to get it working but with this you'll loose support for other tools relyin on ingress, like external-dns.

@monotek  Just wanted to chime in here and say it's definitely possible to get external-dns working alongside ingressRoute by using an empty ingress. For services I run with ingressRoutes, I run an ingress like this as part of the same release:

```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-external-name-dns
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "myapp.example.com"
```

This will route no traffic, but it will get picked up by external-dns as any normal ingress. It's a straightforward workaround for me.
