### ISSUE TITLE
Can't install 2.0.1 version

### ISSUE THREAD

**Issue by kopaygorodsky** [containous/traefik-helm-chart#230]
I install traefik using this cmd: `helm install traefik2 traefik/traefik --namespace kube-system --values=values.yaml`

values.yaml:
```
# Default values for Traefik
image:
  name: traefik
  tag: 2.0.1
```

Logs: `traefik.go:67: command traefik error: error while building entryPoint traefik: error preparing server: error opening listener: listen tcp: address tcp/9000/tcp: unknown port`
