### ISSUE TITLE
How to expose only especific endpoints from my Kubernetes Service on Traefik

### ISSUE THREAD

**Issue by cunhazord** [containous/traefik-helm-chart#232]
Hi! 
Today I'm using Traefik to expose my Kubernetes services to the web, but with default configuration, Traefik exposes all my service endpoints, and I want to expose only especifics endpoints from them. How do I do that? My API have endpoints that I don't want to expose too.

My configuration:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: svc-ingressroute-https
  namespace: production
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`myhost.com`) && PathPrefix(`/svc`)
    kind: Rule
    services:
    - name: svc
      port: port
    middlewares:
      - name: middleware1
```
Thanks!
