### ISSUE TITLE
namespace "production" is ignored in cross-provider context

### ISSUE THREAD

**Issue by heartwilltell** [containous/traefik-helm-chart#42]
1. Create namespace
```shell script
kubectl create namespace traefik
```

2. Install chart
```shell script
helm install --namespace=traefik \
  --set additionalArguments="{--providers.kubernetesingress,--global.checknewversion=true}" \
  traefik ./traefik
```

3. Follow logs of traefik pod
```
time="2019-12-05T17:56:17Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:17Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:17Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" serviceName=api@internal providerName=kubernetescrd
time="2019-12-05T17:56:18Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:19Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:19Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:19Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:19Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:20Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:21Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" serviceName=api@internal providerName=kubernetescrd
time="2019-12-05T17:56:21Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
time="2019-12-05T17:56:21Z" level=warning msg="namespace \"production\" is ignored in cross-provider context" providerName=kubernetescrd serviceName=api@internal
^CGot error: signal: interrupt
```

Any explanation about it?

**Comment by jengo** [comment]
I fixed the cross namespace issue by adding --providers.kubernetesCRD.namespaces=[] which will allow all namespaces

**Comment by ncsibra** [comment]
I have the same problem, IngressRoute definiton:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: public-endpoint
  name: traefik-dashboard-ingress
  namespace: infra
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`test.example.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: apiAuth@file
```
Then it spamming the logs with this in every sec: 
`{"level":"warning","msg":"namespace \"infra\" is ignored in cross-provider context","providerName":"kubernetescrd","serviceName":"api@internal","time":"2020-01-14T14:22:03Z"} `

If I remove the namespace from metadata, then the spamming stops.
But it basically means, that we can't put the IngressRoutes to whenever namespace we want.

This is pretty annoying and makes the logs unreadable.
