### ISSUE TITLE
Unable to bind to port 53

### ISSUE THREAD

**Issue by samip5** [containous/traefik-helm-chart#516]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.6.0

### What version of Traefik are you using?

2.5.3

### What did you do?

I tried to create an TCP and UDP ports for 53

### What did you see instead?

```
2021/10/21 20:04:29 traefik.go:81: command traefik error: error while building entryPoint tcpdns: error preparing server: error opening listener: listen tcp :53: bind: permission denied
```

### What is your environment & configuration?

My values:

```yaml
values:
    deployment:
      kind: Deployment
      replicas: 2
    service:
      enabled: true
      type: LoadBalancer
      spec:
        ipFamilyPolicy: PreferDualStack
        externalIPs:
        - "${SVC_TRAEFIK_ADDRESS}"
        - "${SVC_TRAEFIK_V4}"
        externalTrafficPolicy: Local
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
        filters:
          statuscodes: "404,401,300-302"
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
    - "--api.insecure=true"
    - "--serverstransport.insecureskipverify=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    - "--metrics.prometheus=true"
    - "--metrics.prometheus.entryPoint=metrics"
    - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/13,104.24.0.0/14,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
    additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.ip=${SVC_TRAEFIK_ADDRESS}"
    - "--providers.kubernetesingress.ingressendpoint.ip=${SVC_TRAEFIK_V4}"
    - "--providers.kubernetesingress.allowexternalnameservices=true"
    - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: false
        exposedPort: 8082
      tcpdns:
        port: 53
        exposedPort: 53
        protocol: TCP
      udpdns:
        port: 53
        exposedPort: 53
        protocol: UDP
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
#        sniStrict: true
    pilot:
      enabled: false
      token: ""
    experimental:
      plugins:
        enabled: false
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - traefik
          topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 300Mi
        ```

**Comment by faust64** [comment]
Default values include:

```
securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
```

Being unprivileged, your process/container can not bind on ports below 1024.

You could either use some port translation, exposing port 53 on with your Service while binding on port 1053, or 5353, ... in your container.
Or try to add the CAP_NET_BIND capability to that securityContext - if you don't use PodSecurityPolicies, that's it, otherwise make sure to create a policy allowing Traefik to do this.
Or re-do that securityContext block to run as root -- not recommended.
