### ISSUE TITLE
Service deployment fails when using a loadBalancerIP

### ISSUE THREAD

**Issue by tchellomello** [containous/traefik-helm-chart#53]
When using the `values.yaml`, the user will tend to uncomment some attributes to be used in the Helm chart. 

Currently the `values.yaml` generates a YAML with an incorrect syntax when specifying a `loadBalancerIP` entry.

```yaml
# helm install --name traefik-v22 \
#       --namespace=traefik-v2 ./traefik-helm-chart \
#       --debug --dry-run \
#       --set service.spec.loadBalancerIp=192.168.168.44

[....]

# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-v22
  labels:
    app: traefik
    chart: "traefik-2.2.2"
    release: "traefik-v22"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  loadBalancerIp: 192.168.168.44 <----- error when deploying
  
  selector:
    app: traefik
    release: traefik-v22
  ports:
  - port: 80
    name: web
    targetPort: "web"
  - port: 443
    name: websecure
    targetPort: "websecure"
```

It should be:

```yaml
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-v22
  labels:
    app: traefik
    chart: "traefik-2.2.2"
    release: "traefik-v22"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.168.44 <---- works  fine
  
  selector:
    app: traefik
    release: traefik-v22
  ports:
  - port: 80
    name: web
    targetPort: "web"
  - port: 443
    name: websecure
    targetPort: "websecure"
```
