### ISSUE TITLE
IngressRoute not discovered by Traefik

### ISSUE THREAD

**Issue by kormotodor** [containous/traefik-helm-chart#63]
1. Hi, i have the following simple setup of the chart:
```
helm install traefik -n ingress ./ --set additionalArguments="{--api.insecure=true}
```
2. Also i have a `bar` service from other chart in `foo` namespace:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bar
  name: bar
  namespace: foo
spec:
  clusterIP: 10.210.220.230
  ports:
  - name: http
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: bar
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
3. And Traefik `IngressRoute` CRD in the same namespace with `bar` service:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bar-ingressroute
  namespace: foo
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`bar.my.domain`) && PathPrefix(`/`)
    services:
    - kind: Serivce
      name: bar
      namespace: foo
      passHostHeader: true
      port: 5555
      scheme: http
```
## What i expexted:
1. Exposed `bar` service on `http://bar.my.domain:80`
## What i got:
1. Nothing on `http://bar.my.domain:80`
2. Only internal Traefik services (api@internal, dashboard@internal, ping@internal)
___
Cluster setup:
1. 3 nodes
2. Correct DNS setup from `bar.my.domain` to each node IP

Any ideas where i get wrong?
