### ISSUE TITLE
Publish chart to public repo

### ISSUE THREAD

**Issue by brandond** [containous/traefik-helm-chart#65]
I'm trying to use this with k3's embedded Tiller and the Helm CRD, but it fails as the chart needs to be hosted in a repo somewhere. Would it be possible to publish this (even in its current status) to a public repository?

**Comment by jimbocoder** [comment]
Big :+1: for this! @brandond in the meantime, I just now forked and repo-ified this project in a ghetto way, but it works.  Here it is as a dependency in `Chart.yaml`:

```
dependencies:
  - name: traefik
    version: "3.3.1"
    repository: https://raw.githubusercontent.com/jimbocoder/traefik-helm-chart/master/tiny-repo
```

Hope it helps you until there's motion on this issue.
