### ISSUE TITLE
How to configure static config file

### ISSUE THREAD

**Issue by RuBiCK** [containous/traefik-helm-chart#69]
I want to configure `ingressClass` and `namespaces` that ingress controller is listening. 
I couldn't find any parameter for that in `values.yaml` I was thinking about passing those parameters as environment values but the Chart is not prepared to configure `extraEnv`. 

What is the better way to configure static config within values.yaml?

**Comment by gaui** [comment]
It would be ideal to have near 1:1 mapping between configurable things in the static configuration and the `values.yaml`. But I think the best way currently is to to create a `ConfigMap` and create a `values.yaml` with:

```yaml
persistence:
  enabled: true
  path: /etc/traefik/
```

Or if you prefer another location (`/foo/bar/` is just an example):

```yaml
persistence:
  enabled: true
  path: /foo/bar/

additionalArguments:
  - --configFile=/foo/bar/traefik.yml
```

**Comment by gaui** [comment]
Or maybe it's better to use dynamic configuration. Point the static to that and use `watch`. Something like:

```yaml
providers:
  file:
    filename: /path/to/config/dynamic_conf.yml
    watch: true
```
