### ISSUE TITLE
Adding catch-all router for SSL enforcement?

### ISSUE THREAD

**Issue by andr0272** [containous/traefik-helm-chart#72]
Hello! I am trying to implement the 'I want HTTPS redirection!' section of [this blog post](https://containo.us/blog/traefik-2-0-docker-101-fc2893944b9d/) into helm, and I'm having some issues with routes not automatically receiving the middleware.
This is how im setting it up, in traefik-helm-chart/templates/httpsRedirect.yaml:
```go
{{- if .Values.sslEnforced }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  redirectScheme:
    scheme: https

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "traefik.fullname" . }}-httpsredirect
  labels:
    app: {{ template "traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  entryPoints:
    - web
  routes:
  - match: hostregexp(`{host:.+}`)
    kind: rule
    middlewares:
    - name: redirect-to-https
{{- end -}}
```

When I run helm template, the resources are rendered like this:
```yml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  redirectScheme:
    scheme: https

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: release-name-dts-traefik-httpsredirect
  labels:
    app: dts-traefik
    chart: "dts-traefik-3.1.0"
    release: "release-name"
    heritage: "Tiller"
spec:
  entryPoints:
    - web
  routes:
  - match: hostregexp(`{host:.+}`)
    kind: rule
    middlewares:
    - name: redirect-to-https
```
and the resource I get on my cluster looks like this:
```yml
Name:         dts-traefik-httpsredirect
Namespace:    ingress-merd
Labels:       app=dts-traefik
              chart=dts-traefik-3.1.0
              heritage=Tiller
              release=dts-traefik
Annotations:  <none>
API Version:  traefik.containo.us/v1alpha1
Kind:         IngressRoute
Metadata:
  Creation Timestamp:  2020-01-24T21:09:59Z
  Generation:          4
  Resource Version:    6185161
Spec:
  Entry Points:
    web
  Routes:
    Kind:   rule
    Match:  hostregexp(`{host:.+}`)
    Middlewares:
      Name:  redirect-to-https
Events:      <none>
```
But when I look at the web dashboard, none of my HTTP routers have this middleware applied.
All of my routers run subdomains like `Host(`something.something.domain.com`)`

Has anybody tried implementing this in their cluster? Any luck?

**Comment by mmatur** [comment]
Hi @andr0272 ,

With the next Traefik v2.2 (in RC today) you can enable the redirect on entry-point 

```yaml
image:
  name: traefik
  tag: 2.2

additionalArguments:
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.web.http.redirections.entryPoint.scheme=https
```
