### ISSUE TITLE
Chart 3.3.0 error at upgrade

### ISSUE THREAD

**Issue by jasperkuperus** [containous/traefik-helm-chart#74]
So I've upgraded to version `3.3.0` of this chart and suddenly got this error:

```
coalesce.go:196: warning: cannot overwrite table with non table for env (map[])
```

while running `helm upgrade`.

**Comment by ldez** [comment]
Seems to be related to https://github.com/containous/traefik-helm-chart/pull/71

**Comment by ldez** [comment]
Fixes by 76cc1a80eefe0a00d17c2c5c71340cead1bad22e

**Comment by jasperkuperus** [comment]
This does not solve it for me. It actually introduced a parse error which made me revert to `3.3.0`:

```coalesce.go:196: warning: cannot overwrite table with non table for env (map[])
Error: UPGRADE FAILED: YAML parse error on promo/charts/traefik/templates/deployment.yaml: error converting YAML to JSON: yaml: line 78: did not find expected key
```

**Comment by ldez** [comment]
Could you retry with 3.3.2, thank you.

**Comment by jasperkuperus** [comment]
Seems to get one step further, a new error:

```
coalesce.go:196: warning: cannot overwrite table with non table for env (map[])
Error: YAML parse error on promo/charts/traefik/templates/deployment.yaml: error converting YAML to JSON: yaml: line 90: block sequence entries are not allowed in this context
```

**Comment by ldez** [comment]
Could you retry with 3.3.3?

**Comment by jasperkuperus** [comment]
Lost the YAML parse error, but still got the warning about `env`.

**Comment by dtomcej** [comment]
@jasperkuperus:

Line 78-81 of the template is:
```
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
```

If you don't have env as a top level key, then it won't properly render.

Please note that as this is an incubator chart, upgrade issues are bound to pop up, as the intention to preserve "upgrade/backwards compatability" is minimal.

Could you try with env as the top key, like in the values.yaml in this repo?

**Comment by jasperkuperus** [comment]
Hi @dtomcej. I know this. Let me explain a bit more what I'm doing:

I 'installed' this chart within my chart as a dependency, effectively mimicking how it'll work when we're able to install it through a repository:

```sh
/my-chart
  Chart.yaml
  values.yaml
  ...
  /charts
    postgresql-8.1.4.tgz
    /traefik
      Chart.yaml
      values.yaml
      ...
```

The `/charts/traefik` is literally the `traefik` folder from this repository. My `values.yaml` now looks something like this:

```yaml
postgresql:
  postgresqlDatabase: my-db-name
  ...

traefik:
  dashboard:
    enabled: true
    host: traefik.localhost
  env:
    - name: GCE_PROJECT
      value: secret
    - name: GCE_SERVICE_ACCOUNT_FILE
      value: alsosecret
  additionalArguments:
    - --certificatesresolvers.le.acme.dnschallenge
    - --certificatesresolvers.le.acme.dnschallenge.provider=gcloud
  ...
```

As you can see, `env` is on the same level as `dashboard` and `additionalArguments`, which are both on the root level of the `values.yaml` in this repository.

Please notice that everything works as expected and there are no *errors*. The thing I'm complaining about is the warning, related to `traefik.env`:

```sh
coalesce.go:196: warning: cannot overwrite table with non table for env (map[])
```
