### ISSUE TITLE
How to start traefik dashboard?

### ISSUE THREAD

**Issue by MichelDiz** [containous/traefik-helm-chart#85]
In general, I would do:

```
helm install traefik traefik/traefik --set dashboard.ingressRoute="true"
```

By digging I tried

```
helm install traefik traefik/traefik --set="{--dashboard.ingressRoute=true}"
```

But it won't work at all.

What are the guides here?

**Comment by arlyon** [comment]
Also struggling with this. Can access traefik (as evidenced by the 404 page) but dashboard is also a 404...

**Comment by MichelDiz** [comment]
The "workaround" I did was clone the repo, edit manually and `helm install traefik ./`

**Comment by ldez** [comment]
Hello,

You have to set: `dashboard.enable=true` and `dashboard.ingressRoute=true`

https://github.com/containous/traefik-helm-chart/blob/43d63f418836d7aaac03cfca5b54f4287c8acf9c/traefik/values.yaml#L76-L83

**Comment by MichelDiz** [comment]
Hi @ldez , the issue is that I have to clone instead of following the instructions in the readme. To make it work.

**Comment by MichelDiz** [comment]
You guys could add a new value in https://github.com/containous/traefik-helm-chart/blob/d7fc8d82551dd8c22a842948f32f4dc9233492e7/traefik/templates/dashboard-hook-ingressroute.yaml#L1
with "OR" operator we could do something like

```
helm install traefik traefik/traefik --set expose.dashboard=true
```

Just supposing about it, need to test out the hypothesis.

**Comment by mmatur** [comment]
Hi @MichelDiz,

The dashboard is now deployed by default only on `traefik` entry-point. 

You can do the installation with the following command:
```console
helm install traefik traefik/traefik
```

The dashboard is accessible with the following command:

```console
kubectl port-forward traefik-xxxx-xxx 9000:9000
```

https://localhost:9000/

I'm closing this issue because I think the question is answered.

**Comment by blasrodri** [comment]
@mmatur 
I've installed it using 
```
helm traefik treafik/treafik
```

Then I do:

```
$ kubectl port-forward traefik-6c4575d8b8-5w2z5 9000:9000
```

```
$ curl http://localhost:9000/ping
OK
```

```
$ curl http://localhost:9000/
404 page not found
```

**Comment by mmatur** [comment]
@blasrodri 

The dashboard is exposed on `/dashboard`


```bash
curl http://localhost:9000/dashboard/
```

**Comment by blasrodri** [comment]
Forgot to add:

```
curl http://localhost:9000/dashboard
404 page not found
```

**Comment by blasrodri** [comment]
oh, is the trailing `/`? haha

**Comment by nelsonyaccuzzi** [comment]
Hi, I can't get to the dashboard

I've tried with the trailing dash and it doesn't work, but the ping endpoint works

```
➜ ~ kubectl port-forward $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name -n traefik-v2) 9000:9000 -n traefik-v2
Forwarding from 127.0.0.1:9000 -> 9000
Forwarding from [::1]:9000 -> 9000
```
```
➜  ~ curl http://localhost:9000/ping
OK%                                                                                                                              
➜  ~ curl http://localhost:9000/dashboard
404 page not found
➜  ~ curl http://localhost:9000/dashboard/
404 page not found
```

**Comment by yusiwen** [comment]
still got 404 when accessing `http://localhost:9000/dashboard/`
any updates?

**Comment by dchernivetsky** [comment]
+1 for this. Why is this closed without due investigation.
We have a default chart installation with the following values.yaml:
```
traefik:
  enabled: true
  additionalArguments: 
    - "--providers.kubernetesingress"
    - "--providers.kubernetescrd.ingressclass=traefik-internal"
    - "--providers.kubernetesingress.ingressclass=traefik-internal"
    - "--metrics.prometheus=true"
    - "--metrics.prometheus.entrypoint=metrics"
    - "--entrypoints.metrics.address=0.0.0.0:9100"
  serviceType: LoadBalancer
  nameOverride: traefik-internal
  fullnameOverride: traefik-internal
  replicas: 1
  rbac:
    enabled: true
  resources:
    limits:
      cpu: 300m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 20
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
```
It does seem to install the dashboard ingressroute
```
kubectl get ingressroute -n kube-system
NAME                         AGE
traefik-internal-dashboard   18m
```
However no dashboard shows up when port-forwarded:
```
$ curl http://localhost:9000/dashboard/
404 page not found
$

**Comment by ByronHsu** [comment]
@yusiwen same here

**Comment by xrl** [comment]
I cleared up this error on my side by tearing down the traefik helm release, reinstalling it. Something is screwed up with the CRDs, as the post directly above me indicates. But I wasn't doing anything to change the ingress classes so those changes didn't help me.

**Comment by indigo423** [comment]
Ran into a similar issue deploying the Helm chart. What is really important, add the `/` in the URL when accessing it with port forwarding like here `http://localhost:49599/dashboard/.

**Comment by NicolasTr** [comment]
I ran into a similar issue. I had to add the following to the helm values to be able to port forward to the dashboard:
```
ingressRoute:
  dashboard:
    enabled: true
```

**Comment by broomfn** [comment]
Why do we need the tailing "/" on "/dashboard/", It's really confusing, I thought one of the goals of Traefik was (and I quote) 

"With Traefik, you spend time developing and deploying new features to your system, not on configuring and maintaining its working state."

I've spent hours trying to get this working, and things like having to add tailing backslashes really don't help :-(

**Comment by lzd-1230** [comment]
> I ran into a similar issue. I had to add the following to the helm values to be able to port forward to the dashboard:
> 
> ```
> ingressRoute:
>   dashboard:
>     enabled: true
> ```

That's real methods dude... It's weird that after open `ingressRoute` but without actual ingressRoute resource in k8s when using `kubectl get ingressroute --all-namespace`.

**Comment by idpsycho** [comment]
when running this:
`kubectl port-forward $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000`

i got 404 even with slash at the end: http://127.0.0.1:9000/dashboard/

what fixed it was to create fix-traefik-dashboard.yaml with:
```
dashboard:
 enable: true
ingressRoute:
 dashboard:
   enabled: true
```

and run:
`helm upgrade --install traefik traefik/traefik -f fix-traefik-dashboard.yaml`

now it works (might need restarting port-forward)
(just summarizing, because there wasnt full summary answer anywhere in here)

**Comment by mloiseleur** [comment]
That's right, since [v29.0.0](https://github.com/traefik/traefik-helm-chart/releases/tag/v29.0.0), this `IngressRoute` has been disabled by default. 

@idpsycho This part is not doing anything with this chart:

```yaml
dashboard:
 enable: true
```

You can remove it. BTW, I opened a PR to improve current example on this subject, see #1134 . Wdyt ? Anything to add ?

**Comment by PowerOfCreation** [comment]
For anyone coming here again, this is what worked for me:

Activating the dashboard:

```yaml
  ingressRoute:
    dashboard:
      enabled: true
```

Opening port-forward to `8080` and opening this page [http://localhost:8080/dashboard/](http://localhost:8080/dashboard/).

Not sure if it was changed but traefik exposed the port 8080 instead of 9090 for me.
