### ISSUE TITLE
On 3.0, TlsStore CRD seems to not work

### ISSUE THREAD

**Issue by p4block** [containous/traefik-helm-chart#851]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was using this block to make Traefik serve a certificate stored in the cloudflare-tls secret by default for all tls routers, without having to specify the secret in all ingresses or copy the origin certificate to a dozen namespaces.
```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: kube-system
spec:
  defaultCertificate:
    secretName: cloudflare-tls
```

I'm seeing lots of changes to 3.0 in the docs, but nothing that would suggest this would break. The relevant section is unchanged, but that may be just because it hasn't being changed _yet_

### What did you see instead?

Upon upgrade to 3.0, updating my CRDs (including this one) to `traefik.io` ... it won't work. ~~I also tried using the old CRDs to no avail.~~ EDIT: see below post

### What version of Traefik are you using?

docker.io/traefik:3.0-beta2

### What is your environment & configuration?

values.yaml
```
    image:
      tag: "3.0"

    experimental:
      v3:
        enabled: true

    deployment:
      enabled: true
      kind: DaemonSet

    updateStrategy:
      type: OnDelete
          
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - traefik
            topologyKey: kubernetes.io/hostname

    ports:
      metrics:
        # When using hostNetwork, use another port to avoid conflict with node exporter:
        # https://github.com/prometheus/prometheus/wiki/Default-port-allocations
        port: 9101
      web:
        port: 80
        redirectTo: websecure
      websecure:
        port: 443

    # Not very useful under HostNetwork
    service:
      enabled: false

    logs:
      general:
        level: DEBUG

    tlsStore:
      default:
        defaultCertificate:
          secretName: cloudflare-tls

    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0

```

### If applicable, please paste the log output in DEBUG level

```
2023-05-23T23:36:35Z DBG github.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:217 > Configuration received config={"http":{},"tcp":{},"udp":{}} providerName=kubernetes
2023-05-23T23:36:35Z DBG github.com/traefik/traefik/v2/pkg/tls/tlsmanager.go:294 > No default certificate, fallback to the internal generated certificate tlsStoreName=default
```
